apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    editable: true
    uid: clickhouse-benchmark

    # If you prefer to use HTTP instead of TCP, uncomment the following line and comment the above line.
    # url: http://${CLICKHOUSE_HOST_DOCKER}:${CLICKHOUSE_HTTP_PORT_DOCKER}

    isDefault: true
    jsonData:
    
      host: ${CLICKHOUSE_HOST_DOCKER}
      port: ${CLICKHOUSE_TCP_PORT_DOCKER}
      protocol: native

      # If you prefer to use HTTP instead of TCP, uncomment the following 3 lines and comment the above 3 lines.
      # host: ${CLICKHOUSE_HOST_DOCKER}
      # port: ${CLICKHOUSE_HTTP_PORT_DOCKER}
      # protocol: http

      timeColumn: timestamp